/** Espelho do backend — permissões padrão do perfil Operacional */
export const OPERACIONAL_PERMISSIONS = [
  'dashboard:READ',
  'products:READ',
  'products:CREATE',
  'products:UPDATE',
  'stock:READ',
  'stock:CREATE',
  'stock:UPDATE',
  'settings:READ',
  'settings:CREATE',
  'settings:UPDATE',
  'movements:READ',
  'movements:CREATE',
  'movements:APPROVE',
  'inventory:READ',
  'inventory:CREATE',
  'inventory:UPDATE',
  'reports:READ',
  'reports:EXPORT',
  'batches:READ',
  'batches:CREATE',
  'batches:UPDATE',
] as const;
